config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do

    root 'welcomes#index'

    resources :welcomes, only: [:index, :create]
    resource :session, only: [:create, :destroy]
    resources :features, only: [:index]
    resources :residents, only: [:index]
    resources :merchants, only: [:index, :create]
    resources :media, only: [:index]
    resources :contacts, only: [:index, :create]
    resources :bulletins, only: [:index, :show]
    resources :events, only: [:index, :show]
    get 'join/:id',              to: 'events#join',           as: 'join_event'
    get  'events/:id/photo' , to: 'events#image_details' , as: 'event_photos'
    resources :feedbacks, only: [:new, :create]
    resources :services , only: [:index , :show]
    get 'service/get_service' , to: "services#get_service"
    resources :forms , only: [:index]
    resources :house_rules , only: [:index , :show]
    resource :user, only: [:show, :edit, :update] do
      member do
        get 'password'
        get 'e_walet' => 'users#e_walet'
        patch 'update_password'
        put 'update_password'
        get 'get_users' => 'users#get_users', as: 'get_users'
      end
    end
    resource :help, only: [] do
      member do
        get 'support'
        get 'about'
      end
    end

    resources :homes, only: [:index]

    resources :privileges, only: [:index, :show] do
      collection do
        post 'redeem_previlege'
        get 'my_privileges'
        post 'delete_my_privilege'
      end
    end

    resources :courses, only: [:index, :show]

    get 'bookings/check_booking' => 'bookings#check_booking'
    post 'bookings/make_a_booking' => 'bookings#make_a_booking'
    post 'bookings/delete_my_booking' => 'bookings#delete_my_booking'
    resources :bookings do
    end

    resources :guard_houses do
      collection do
      end
   end

  end
  get 'service/get_service' , to: "services#get_service"
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
respond_to :js , :html , :json
before_action :set_menu
def index

 @cat  = get_api('/service_categories', { :condo_id => session[:condo_id] , :auth_token =>session[:auth_token]})
end
def get_service
 @services = get_api('/services' , {:service_category_id => params[:id] , :auth_token =>session[:auth_token]})
end  
def show
  @service = get_api('/service_detail' , { :service_id => params[:id] ,:auth_token =>session[:auth_token] } )
end  
  private
  def set_menu
    session[:menu] = :services
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_services_content.html.erb
<h3><%= t('service.index.search_result') %> </h3>
<% @services[:results].each do |s| %>
<div>

<%= link_to s[:name] , service_path(s[:id]) %>
</div>
 <% end %> 

app/views/services/get_service.js.erb
$('div.result').html('')
<% if @services[:results].size >0 %>

$('div.result').html('<%= j render("services_content") %>')

<% else %>



<% end %>

app/views/services/index.html.erb
<div class= "service-partial">
<h2 class="header"><span class="glyphicon glyphicon-road"></span> &nbsp;<span><%= t('service.index.title') %></span></h2>

<div class="select">
<p><%= t('service.index.looking') %> </p>
<select class="form-control">
    <option value="all" id="all"  'selected' %>
      <%= t("service.index.please_select") %>
          </option>
    <% @cat[:results].each do |r| %>
        <option  id="<%= r[:id] %>" value="<%= r[:id] %>">
        <%= r[:name] %>

        </option>
    <% end %>
  </select>
</div>
<div class="result">
</div>

<script type="text/javascript">
$(document).ready(function(){
  $('.select select').change(function(){
          var cid = $(this).val();
        if (cid != 'all'){
        param = {"id":cid};
         $.ajax({
        
      url : "service/get_service" ,
      type : "get" ,
      data: param ,
      dataType: "script",
      success: function(){ } ,
      error: function(){ }
    });
       }
       else{
        $('div.result').html('');
       }
  });
});
</script>
</div>

app/views/services/show.html.erb
<div class= "service-partial">
<h2 class="header"><span class="glyphicon glyphicon-road"></span> &nbsp;<%= link_to t('service.index.title') , services_path , class: "btn-link nice-red" %> <span> > <%= t('event.index.info') %> </span>

</h2>

<div class="service-content">
<div class="row">
<div class="col-xs-4">
 <%= image_tag url+ @service[:results][:image_path], :class => 'img-thumbnail' %>
</div>
<div class="col-xs-8">
    <h3><%= @service[:results][:name]%></h3>


    <p class="decscription">
  <%= @service[:results][:description]  %>
    </p>

  
</div>
</div>
<p class="left"> <span class="glyphicon glyphicon-map-marker big"></span>
<%= @service[:results][:address] %> 
</p>
<p class="right"><span class="glyphicon glyphicon-dashboard big"></span> 
<%= @service[:results][:order_hours] %> 
</p>
<div class="clear"></div>
<p class="left"> <span class="glyphicon glyphicon-earphone big"></span>
<%= @service[:results][:call_to_order] %> 
</p>
<p class="right"><span class="glyphicon glyphicon-credit-card big"></span> 
<%= mail_to "me@domain.com",  t('service.show.make_order') , 
         subject: "I want to ordre" %>
<%=%> 
</p>
<div class="clear"></div>
<p > <span class="glyphicon glyphicon-globe big"></span>

<%= link_to @service[:results][:web_page], "http://google.com" %>
</p>
<div id="foot">
<h4><a href="#"><%= t('service.show.view_term') %></a></h4>
<p class="term">
<%= @service[:results][:term] %> 
</p>
</div>
</div>

</div>
<script type="text/javascript">
$(document).ready(function(){
  $("p.term").hide();
  $("#foot a").click(function(e){
    e.preventDefault();
     $("p.term").slideToggle();
  });
});
</script>