config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do

    root 'welcomes#index'

    resources :welcomes, only: [:index, :create]
    resource :session, only: [:create, :destroy]
    resources :features, only: [:index]
    resources :residents, only: [:index]
    resources :merchants, only: [:index, :create]
    resources :media, only: [:index]
    resources :contacts, only: [:index, :create]
    resources :bulletins, only: [:index, :show]
    resources :events, only: [:index, :show]
    get 'join/:id',              to: 'events#join',           as: 'join_event'
    get  'events/:id/photo' , to: 'events#image_details' , as: 'event_photos'
    resources :feedbacks, only: [:new, :create]
    resources :services , only: [:index , :show]
    get 'service/get_service' , to: "services#get_service"
    resources :forms , only: [:index]
    resources :house_rules , only: [:index , :show]
    resource :user, only: [:show, :edit, :update] do
      member do
        get 'password'
        get 'e_walet' => 'users#e_walet'
        patch 'update_password'
        put 'update_password'
        get 'get_users' => 'users#get_users', as: 'get_users'
      end
    end
    resource :help, only: [] do
      member do
        get 'support'
        get 'about'
      end
    end

    resources :homes, only: [:index]

    resources :privileges, only: [:index, :show] do
      collection do
        post 'redeem_previlege'
        get 'my_privileges'
        post 'delete_my_privilege'
      end
    end

    resources :courses, only: [:index, :show]

    get 'bookings/check_booking' => 'bookings#check_booking'
    post 'bookings/make_a_booking' => 'bookings#make_a_booking'
    post 'bookings/delete_my_booking' => 'bookings#delete_my_booking'
    resources :bookings do
    end

    resources :guard_houses do
      collection do
      end
   end

  end
  get 'service/get_service' , to: "services#get_service"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_menu
  respond_to :html, :js

  def index
    #get total page from api

    limit = 5

    if params[:page]
      @current_page = params[:page]
    else
      @current_page = 1
    end
    @events = hash_to_object get_api('/events', {:page => @current_page, :limit => limit, :auth_token => session[:auth_token], :condo_id => session[:condo_id]})
    @pages = @events[:total] % limit == 0 ? @events[:total]/limit : @events[:total]/limit +1
    @total_event = @events[:total].blank? ? 0 : @events[:total]
    @events = @events.results.blank? ? nil : @events.results
  end

  def show
    event = hash_to_object get_api('/event_detail', {:event_id => params[:id], :auth_token => session[:auth_token]})
    @list_user = get_api('/list_user', {:event_id => params[:id], :auth_token => session[:auth_token]})
    all_image = hash_to_object get_api('/event_detail_photo', {:event_id => params[:id], :auth_token => session[:auth_token]})
    @all_image = all_image.results.blank? ? nil : all_image.results
    @event = event.results.blank? ? nil : event.results
  end

  def join
    @join_event = post_api('/join_event', {:user_id => session[:user_id], :event_id => params[:id], :auth_token => session[:auth_token]})
    @list_user = get_api('/list_user', {:event_id => params[:id], :auth_token => session[:auth_token], :user_id => session[:user_id]})
  end

  def photo
  end


  private
  def set_menu
    session[:menu] = :events
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<!--<div class="event-partial">-->
  <!--<h2 class="header"><span class="fa fa-flag-o"></span> &nbsp;<span><%= t('event.index.title') %></span></h2>-->

  <!--<%# unless @events.nil? %>-->
      <!--<%# @events.each do |e| %>-->
          <!--<div class="event-content">-->
            <!--<div class="row">-->
              <!--<div class="col-xs-2">-->
                <!--<%#= image_tag url+e[:image], :class => 'img-thumbnail' %>-->
              <!--</div>-->
              <!--<div class="col-xs-10">-->
                <!--<h3><%#= link_to e[:name], event_path(e[:id]), {class: "btn-link"} %></h3>-->

                <!--<span><%#= t('event.index.daypost') %> : <i><%#= e[:date] %></i></span>-->

              <!--</div>-->

            <!--</div>-->
          <!--</div>-->
      <!--<%# end %>-->
      <!--<div class="text-center">-->
        <!--<ul class="pagination">-->
          <!--<li class='<%#= @current_page.to_i == 1 ? "disabled" : "" %>'>-->
            <!--<a href='<%#= @current_page.to_i == 1 ? "#" : "/events?page=#{@current_page.to_i - 1}" %>'>&laquo</a>-->
          <!--</li>-->
          <!--<%# for i in 1..@pages %>-->
              <!--<%# if i == @current_page.to_i %>-->
                  <!--<li class="active">-->
                    <!--<a href=""><%#= i %><span class="sr-only">(current)</span></a>-->
                  <!--</li>-->
              <!--<%# else %>-->
                  <!--<li>-->
                    <!--<%#= link_to i, events_path(:page => i) %>-->
                  <!--</li>-->
              <!--<%# end %>-->

          <!--<%# end %>-->
          <!--<li class='<%#= @current_page.to_i == @pages ? "disabled" : "" %>'>-->
            <!--<a href='<%#= @current_page.to_i == @pages ? "#" : "/events?page=#{@current_page.to_i + 1}" %>'>&raquo</a>-->
          <!--</li>-->
        <!--</ul>-->
      <!--</div>-->
  <!--<%# end %>-->
<!--</div>-->


<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title"><%= t('layout_application.events') %></h3>
        <div class="box-tools pull-right">
          <span class="label label-success"><%= @total_event.to_s + ' ' + t('layout_application.events') %></span>
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <!--<button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>-->
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
          <% unless @events.nil? %>
              <% i = 0; @events.each do |event| i += 1;%>
                  <div class="row">
                    <div class="col-md-2">
                      <%= image_tag url+event[:image], :class => 'img-thumbnail' %>
                    </div>
                    <div class="col-md-10">
                      <h5><b><%= link_to event[:name], event_path(event[:id]) %></b></h5>
                      <h5><%= t 'layouts.homes.date_apply'%><%= DateTime.parse(event.date).strftime("%d/%m/%Y") if !event.date.nil? %>  <%= DateTime.parse(event.time_start).strftime('%H:%M') if !event.time_start.nil? %> - <%= DateTime.parse(event.time_end).strftime('%H:%M') if !event.time_end.nil? %></h5>
                      <h5><%= t('events.location') %> <%= event.location %></h5>
                      <span><%= event.description %></span>
                    </div>
                    <% if @events.size > i %>
                        <div class='col-md-12'><hr/></div>
                    <% end %>
                  </div>
              <% end %>
            <% else %>
            <div class='col-md-12'><%= t('data.empty') %></div>
          <% end %>
      </div>
      <!-- /.box-body -->
      <div class="box-footer text-center">
        <ul id="pagination" class="pagination-sm" style="margin: 0px;"></ul>
        <script>
            $(function(){
                $('#pagination').twbsPagination({
                    totalPages: parseInt('<%= @pages %>'),
                    visiblePages: 5,
                    startPage: parseInt('<%= @current_page %>'),
                    href: '?page={{number}}',
                    first: i18nJs.layout.first,
                    prev: i18nJs.layout.prev,
                    next: i18nJs.layout.next,
                    last: i18nJs.layout.last
                });
            })
        </script>
      </div>
    </div>
  </div>
</div>

app/views/events/join.js.erb
<% if @join_event[:status] == "success" %>
$("a.join").remove() ; 
$("span.num").text('<%= @list_user[:results][:num_user] %>');
$("i.include").text('<%= t("event.show.including") %>');

<% else %>
alert("Join fails");

<% end %>

app/views/events/show.html.erb
<!--<div class="event-partial">-->
  <!--<h2 class="header">-->
    <!--<span class="fa fa-flag-o"></span> &nbsp;<%#= link_to t('event.index.title'), events_path, class: "btn-link nice-red" %>
    <!--<span> <i class="fa fa-angle-right"></i> <%#= t('event.index.info') %> </span>-->

    <!--<%#= link_to "#", {class: 'btn-link left nice-red', remote: true} do %>-->
        <!--<span class="glyphicon glyphicon-film"></span> <%#= t('event.show.view_photo') %>
    <!--<%# end %>-->


  <!--</h2>-->

  <!--<div class="event-content">-->
    <!--<div class="row">-->
      <!--<div class="col-xs-4">-->
        <!--<%#= image_tag url+@all_image[:results][0][:image_url], :class => 'img-thumbnail' %>-->
      <!--</div>-->
      <!--<div class="col-xs-8">-->
        <!--<h3><%#= @event[:results][:name] %></h3>-->

        <!--<div class="date-post"><%#= t('event.index.daypost') %> :-->
          <!--<i><%#= @event[:results][:created_at].to_datetime.strftime('%d/%m/%Y ') %></i></div>-->
        <!--<p class="list_user"><span class="glyphicon glyphicon-user big"></span>-->
          <!--<span class="num"><%#= @list_user[:results][:num_user] %> </span>-->
          <!--<%#= t('event.show.resident_atend') %>-->
          <!--<i class="include"><%#= @list_user[:results][:user_join] ? t('event.show.including') : "" %></i>-->
        <!--</p>-->
        <!--<%# unless @list_user[:results][:user_join] %>-->
            <!--<%#= link_to t('event.show.im_comming'), join_event_path(@event[:results][:id]), class: "btn btn-info join", remote: true %>-->
        <!--<%# end %>-->
      <!--</div>-->
    <!--</div>-->
    <!--<p id="left"><span class="glyphicon glyphicon-map-marker big"></span>-->
      <!--<%#= @event[:results][:location] %>-->
    <!--</p>-->

    <!--<p id="medium"><span class="glyphicon glyphicon-calendar big"></span>-->
      <!--<%#= @event[:results][:date] %>-->
    <!--</p>-->

    <!--<p id="right"><span class="glyphicon glyphicon-dashboard big"></span>-->
      <!--<%#= @event[:results][:event_start].to_datetime.strftime('%I:%M %P') unless @event[:results][:event_start].nil? %>-->
      <!----->
      <!--<%#= @event[:results][:event_end].to_datetime.strftime('%I:%M %P') unless @event[:results][:event_start].nil? %>-->
    <!--</p>-->

    <!--<p id="foot"><%#= @event[:results][:description] %></p>-->
  <!--</div>-->

<!--</div>-->
<!--<script type="text/javascript">-->
<!--//    $(document).ready(function () {-->
<!--//        var dynamicimg = []-->
        <!--<%# @all_image[:results].each do |img| %>-->
<!--//        dynamicimg.push({"src": '<%#= url+img[:image_url] %>', "thumb": '<%#= url+img[:image_url_thumb] %>'})-->
        <!--<%# end %>-->
<!--//        $('a.left').click(function (e) {-->
<!--//            $(this).lightGallery({-->
<!--//                dynamic: true,-->
<!--//                mobileSrc: true,-->
<!--//                dynamicEl: dynamicimg-->
<!--//            });-->
<!--//        });-->
<!--//    });-->
<!--</script>-->



<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title"><a href="" onclick="goBack()" class="fa fa-reply"></a> <%= t('layout_application.events') %></h3>
        <div class="box-tools pull-right">
          <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <!--<button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>-->
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <div class="row">
          <% unless @event.nil? %>
            <div class="col-md-2">
              <%= image_tag (@all_image.nil? ? 'no-image.jpg' : image_base_url + @all_image[0].image_url_thumb), :class => 'img-thumbnail' %>
            </div>
            <div class="col-md-10">
              <h5><b><%= @event[:name] %></b></h5>
              <h5><%= t 'layouts.homes.date_apply'%><%= DateTime.parse(@event.date).strftime("%d/%m/%Y") if !@event.date.nil? %>  <%= DateTime.parse(@event.event_start).strftime('%H:%M') if !@event.event_start.nil? %> - <%= DateTime.parse(@event.event_end).strftime('%H:%M') if !@event.event_end.nil? %></h5>
              <h5><%= t('events.location') %> <%= @event.location %></h5>
              <span><%= @event.description %></span>
            </div>
          <% end %>
        </div>
          <% unless @all_image.nil? %>
            <div class="row">
              <div class="col-md-12"><h5 style="margin-bottom: 0px;"><%= t('events.click_image_to_slideshow') %></h5></div>
              <%  @all_image.each do |img| %>
              <div class="col-md-2" style="padding-top: 20px;">
                <a href="<%= image_base_url + img.image_url %>">
                  <%= image_tag image_base_url + img.image_url_thumb, {:class => 'img-thumbnail', 'data-smoothzoom' => 'group1', :alt => ''} %>
                </a>
              </div>
            <% end %>
            </div>
          <% end %>

      </div>
      <!-- /.box-body -->
    </div>
  </div>
</div>

<style>
  .sz-overlay, .sz-left, .sz-right, .sz-zoomed{
      z-index: 9999;
  }

</style>
<script>
    $(window).load( function() {
        $('img').smoothZoom({
            closeButton: true
        });
    });
</script>