config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do

    root 'welcomes#index'

    resources :welcomes, only: [:index, :create]
    resource :session, only: [:create, :destroy]
    resources :features, only: [:index]
    resources :residents, only: [:index]
    resources :merchants, only: [:index, :create]
    resources :media, only: [:index]
    resources :contacts, only: [:index, :create]
    resources :bulletins, only: [:index, :show]
    resources :events, only: [:index, :show]
    get 'join/:id',              to: 'events#join',           as: 'join_event'
    get  'events/:id/photo' , to: 'events#image_details' , as: 'event_photos'
    resources :feedbacks, only: [:new, :create]
    resources :services , only: [:index , :show]
    get 'service/get_service' , to: "services#get_service"
    resources :forms , only: [:index]
    resources :house_rules , only: [:index , :show]
    resource :user, only: [:show, :edit, :update] do
      member do
        get 'password'
        get 'e_walet' => 'users#e_walet'
        patch 'update_password'
        put 'update_password'
        get 'get_users' => 'users#get_users', as: 'get_users'
      end
    end
    resource :help, only: [] do
      member do
        get 'support'
        get 'about'
      end
    end

    resources :homes, only: [:index]

    resources :privileges, only: [:index, :show] do
      collection do
        post 'redeem_previlege'
        get 'my_privileges'
        post 'delete_my_privilege'
      end
    end

    resources :courses, only: [:index, :show]

    get 'bookings/check_booking' => 'bookings#check_booking'
    post 'bookings/make_a_booking' => 'bookings#make_a_booking'
    post 'bookings/delete_my_booking' => 'bookings#delete_my_booking'
    resources :bookings do
    end

    resources :guard_houses do
      collection do
      end
   end

  end
  get 'service/get_service' , to: "services#get_service"
end

app/controllers/welcomes_controller.rb
class WelcomesController < RootsController
  # layout 'adminLte' #welcome
  before_action :set_menu
  skip_before_action :authenticate_user!
  before_action :redirect_to_home

  def index
    json_condo = api_get '/condos'
    if json_condo[:status] = 'success'
      @condos = []
      json_condo[:results].each do |condo|
        @condos << condo.values
      end
    end
  end

  def create
    json_user = api_post '/sign_up', user_params
    @user = json_user[:status]
    @errors = json_user[:message] unless @user == 'success'
  end

  private
    def set_menu
      session[:menu] = :welcomes
    end

    def user_params
      params.require(:user).permit(:name, :email, :phone, :city, :password, :password_confirmation, :condo_id)
    end

    def redirect_to_home
      unless session[:auth_token].blank?
        redirect_to homes_url
      end
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= form_tag welcomes_path, remote: true do %>
  <div class="form-group">
    <%= label :user, :choose_condo %>
    <%= collection_select :user, :condo_id, @condos, :first, :last, {}, { class: 'form-control' } %>
  </div>
  <%= label :user, :description %>
  <div class="form-group">
    <%= text_field :user, :name, { class: 'form-control', placeholder: t('.name') } %>
  </div>
  <div class="form-group">
    <%= text_field :user, :email, { class: 'form-control', placeholder: t('.email') } %>
  </div>
  <div class="form-group">
    <%= text_field :user, :phone, { class: 'form-control', placeholder: t('.phone_num') } %>
  </div>
  <div class="form-group">
    <%= text_field :user, :city, { class: 'form-control', placeholder: t('.address') } %>
  </div>
  <div class="form-group">
    <%= password_field :user, :password, { class: 'form-control', placeholder: t('.password') } %>
  </div>
  <div class="form-group">
    <%= password_field :user, :password_confirmation, { class: 'form-control', placeholder: t('.password_confirmation') } %>
  </div>
  <div class="text-center form-group">
    <%= button_tag t('.submit'), { type: :submit, name: 'user[submit]', value: 'Submit', class: 'btn btn-primary btn-block' } %>
  </div>
<% end %>

app/views/welcomes/create.js.erb
$('.text-danger').remove()
<% if @user == 'success' %>
  $('#notifications').html('<%= alert_bs t('.respond_ok') %>')
  $('#user_password_confirmation').closest('form')[0].reset()
<% else %>
  $('#notifications').html('<%= alert_bs t('.respond_not_ok') %>')
  <% @errors.each do |key, value| %>
    $('#user_<%= key %>').after('<%= contextual t(".#{key}") + ' ' + value.last %>')
  <% end %>
<% end %>
setTimeout(function() {
  $('#notifications').html('')
}, 3000)

app/views/welcomes/index.html.erb
<!--<div class="col-xs-12 col-sm-6">-->
  <!--<h2 class="text-center"><%= t('.name_app') %></h2>-->
  <!--<h4 class="text-center"><%= t('.info') %></h4>-->
  <!--<h4 class="text-center"><%= t('.description') %></h4>-->
  <!--<p class="text-center"><%= t('.made_private') %></p>-->
  <!--<br>-->
  <!--<strong class="text-justify"><%= t('.download_app') %></strong>-->
<!--</div>-->
<!--<div class="col-xs-12 col-sm-6">-->
  <!--<h1 class="text-center"><%= t('.sign_up_now') %></h1>-->
  <!--<%#= render 'form' %>-->
<!--</div>-->