config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do

    root 'welcomes#index'

    resources :welcomes, only: [:index, :create]
    resource :session, only: [:create, :destroy]
    resources :features, only: [:index]
    resources :residents, only: [:index]
    resources :merchants, only: [:index, :create]
    resources :media, only: [:index]
    resources :contacts, only: [:index, :create]
    resources :bulletins, only: [:index, :show]
    resources :events, only: [:index, :show]
    get 'join/:id',              to: 'events#join',           as: 'join_event'
    get  'events/:id/photo' , to: 'events#image_details' , as: 'event_photos'
    resources :feedbacks, only: [:new, :create]
    resources :services , only: [:index , :show]
    get 'service/get_service' , to: "services#get_service"
    resources :forms , only: [:index]
    resources :house_rules , only: [:index , :show]
    resource :user, only: [:show, :edit, :update] do
      member do
        get 'password'
        get 'e_walet' => 'users#e_walet'
        patch 'update_password'
        put 'update_password'
        get 'get_users' => 'users#get_users', as: 'get_users'
      end
    end
    resource :help, only: [] do
      member do
        get 'support'
        get 'about'
      end
    end

    resources :homes, only: [:index]

    resources :privileges, only: [:index, :show] do
      collection do
        post 'redeem_previlege'
        get 'my_privileges'
        post 'delete_my_privilege'
      end
    end

    resources :courses, only: [:index, :show]

    get 'bookings/check_booking' => 'bookings#check_booking'
    post 'bookings/make_a_booking' => 'bookings#make_a_booking'
    post 'bookings/delete_my_booking' => 'bookings#delete_my_booking'
    resources :bookings do
    end

    resources :guard_houses do
      collection do
      end
   end

  end
  get 'service/get_service' , to: "services#get_service"
end

app/controllers/merchants_controller.rb
class MerchantsController < RootsController
  # layout 'welcome'
  before_action :set_menu
  skip_before_action :authenticate_user!

  def index
  end

  def create
    @merchant = api_post '/request_merchant', merchant_params
    @errors = @merchant[:message] unless @merchant[:status] == 'success'
  end

  private
    def set_menu
      session[:menu] = :merchants
    end

    def merchant_params
      params.require(:merchant).permit(:name, :email, :phone, :archive)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_tag merchants_path, remote: true do %>
  <%= label :merchant, :if_interest %>
  <div class="form-group">
    <%= text_field :merchant, :name, { class: 'form-control', placeholder: t('.name') } %>
  </div>
  <div class="form-group">
    <%= text_field :merchant, :email, { class: 'form-control', placeholder: t('.email') } %>
  </div>
  <div class="form-group">
    <%= text_field :merchant, :phone, { class: 'form-control', placeholder: t('.phone_num') } %>
  </div>
  <div class="text-center form-group">
    <%= button_tag t('.submit'), { type: :submit, name: 'merchant[submit]', value: 'Submit', class: 'btn btn-primary btn-block' } %>
  </div>
<% end %>

app/views/merchants/create.js.erb
$('.text-danger').remove()
<% if @merchant[:status] == 'success' %>
  $('#notifications').html('<%= alert_bs t('.respond_ok') %>')
  $('#merchant_phone').closest('form')[0].reset()
<% else %>
  $('#notifications').html('<%= alert_bs t('.respond_not_ok') %>')
  <% @errors.each do |key, value| %>
    $('#merchant_<%= key %>').after('<%= contextual t(".#{key}") + ' ' + value.last %>')
  <% end %>
<% end %>
setTimeout(function() {
  $('#notifications').html('')
}, 3000)

app/views/merchants/index.html.erb
<h1 class="text-center"><%= t('.merchant') %></h1>
<hr>
<div class="row">
  <div class="col-xs-12 col-sm-7">
    <p class="lead text-justify"><%= t('.info') %></p>
    <p class="text-success"><%= t('.description') %></p>
  </div>
  <div class="col-xs-12 col-sm-5">
    <%= render 'form' %>
  </div>
</div>